import { DemoListing } from '../models/index.js';

const NOTE = 'Test vendor for birthday planning - development data only';

const delhi = (locality, lat, lng, radius = 18) => ({
  location: {
    locality,
    city: 'Delhi',
    address: `${locality}, Delhi`,
    coordinates: { lat, lng },
  },
  serviceRadiusKm: radius,
});

const AREA = {
  hariNagar: delhi('Hari Nagar', 28.6307, 77.1149, 16),
  janakpuri: delhi('Janakpuri', 28.6219, 77.0878, 18),
  rajouri: delhi('Rajouri Garden', 28.6425, 77.1195, 16),
  subhash: delhi('Subhash Nagar', 28.6412, 77.1076, 14),
  tilak: delhi('Tilak Nagar', 28.6365, 77.0965, 14),
  dwarka: delhi('Dwarka', 28.5921, 77.0460, 24),
  motiNagar: delhi('Moti Nagar', 28.6570, 77.1424, 18),
  karolBagh: delhi('Karol Bagh', 28.6514, 77.1907, 22),
  rohini: delhi('Rohini', 28.7041, 77.1025, 24),
  pitampura: delhi('Pitampura', 28.7033, 77.1324, 22),
};

const listing = ({
  ref,
  category,
  vendor,
  packageName,
  base,
  travel = 0,
  additional = 0,
  area = AREA.hariNagar,
  includes = [],
  strengths = [],
  limitations = [],
  negotiable = [],
}) => ({
  externalRef: ref,
  category,
  vendorName: vendor,
  packageName,
  costBreakdown: { base, travel, additional },
  includes,
  strengths,
  limitations,
  negotiable,
  ...area,
});

/** Fresh birthday planning test catalog. Four options per birthday service category. */
export const DEMO_LISTINGS = [
  listing({
    ref: 'venue_01',
    category: 'venue',
    vendor: 'Tiny Palace Party Hall',
    packageName: 'Indoor Birthday Hall for 80',
    base: 42000,
    area: AREA.hariNagar,
    includes: ['4-hour hall access', 'Basic seating', 'Changing room', 'Power backup'],
    strengths: ['Closest to West Delhi birthday families', 'Simple indoor setup', 'Good for kids and elders'],
    limitations: ['Decor billed separately'],
    negotiable: ['extra setup hour', 'weekday hall discount'],
  }),
  listing({
    ref: 'venue_02',
    category: 'venue',
    vendor: 'Happy Nest Banquet',
    packageName: 'Birthday Banquet with Dining Area',
    base: 68000,
    area: AREA.janakpuri,
    includes: ['Banquet hall', 'Dining section', 'Parking help', 'Stage corner'],
    strengths: ['Good dining flow', 'Covered venue', 'Family friendly'],
    limitations: ['DJ volume restrictions after 10 pm'],
    negotiable: ['parking bundle', 'extra cleaning support'],
  }),
  listing({
    ref: 'birthday_venue_03',
    category: 'venue',
    vendor: 'Balloon Bay Studio',
    packageName: 'Kids Party Studio',
    base: 36000,
    area: AREA.rajouri,
    includes: ['Soft play corner', 'Cake table', 'Photo wall', 'Host desk'],
    strengths: ['Best for 25-50 guests', 'Ready-made birthday layout'],
    limitations: ['Limited space for large dancing'],
    negotiable: ['soft play extension', 'return gift table'],
  }),
  listing({
    ref: 'birthday_venue_04',
    category: 'venue',
    vendor: 'Garden Glow Courtyard',
    packageName: 'Open-Air Birthday Lawn',
    base: 78000,
    area: AREA.dwarka,
    includes: ['Outdoor lawn', 'Covered food zone', 'Basic lighting', 'Valet coordination'],
    strengths: ['Premium evening vibe', 'Good photo corners'],
    limitations: ['Weather backup must be confirmed'],
    negotiable: ['lighting upgrade', 'rain-cover add-on'],
  }),

  listing({
    ref: 'cat_01',
    category: 'catering',
    vendor: 'Birthday Bites Catering',
    packageName: 'Veg Party Buffet for 100',
    base: 72000,
    area: AREA.rajouri,
    includes: ['Veg buffet', 'Welcome drinks', 'Live pasta counter', 'Service staff'],
    strengths: ['Balanced family menu', 'Kids-friendly snacks'],
    limitations: ['Non-veg not included'],
    negotiable: ['welcome drink refill', 'chaat counter swap'],
  }),
  listing({
    ref: 'corp_cat_del_01',
    category: 'catering',
    vendor: 'Treat Table Delhi',
    packageName: 'Premium Birthday Buffet',
    base: 96000,
    area: AREA.subhash,
    includes: ['Veg and non-veg buffet', 'Dessert station', 'Mocktail bar', 'Uniformed staff'],
    strengths: ['Close to Hari Nagar', 'Premium menu coverage'],
    limitations: ['Higher per-plate total'],
    negotiable: ['dessert count', 'mocktail duration'],
  }),
  listing({
    ref: 'birthday_cat_03',
    category: 'catering',
    vendor: 'Kids Platter Co.',
    packageName: 'Kids Snack and Meal Counter',
    base: 52000,
    area: AREA.tilak,
    includes: ['Mini burgers', 'Pasta', 'Fries counter', 'Juice station'],
    strengths: ['Strong kids menu', 'Fast counter service'],
    limitations: ['Adult buffet is limited'],
    negotiable: ['extra snack item', 'juice refill'],
  }),
  listing({
    ref: 'birthday_cat_04',
    category: 'catering',
    vendor: 'Family Feast Kitchen',
    packageName: 'North Indian Family Dinner',
    base: 84000,
    area: AREA.motiNagar,
    includes: ['Starters', 'Main course', 'Indian breads', 'Desserts'],
    strengths: ['Good elder-friendly menu', 'Reliable full dinner service'],
    limitations: ['Live counters cost extra'],
    negotiable: ['starter count', 'extra service staff'],
  }),

  listing({
    ref: 'dec_01',
    category: 'decor',
    vendor: 'Party Pop Decor',
    packageName: 'Balloon Theme Decor',
    base: 28000,
    area: AREA.hariNagar,
    includes: ['Balloon arch', 'Cake table styling', 'Name backdrop', 'Welcome board'],
    strengths: ['Fast setup', 'Bright birthday look'],
    limitations: ['Fresh flowers not included'],
    negotiable: ['extra balloon cluster', 'custom name board'],
  }),
  listing({
    ref: 'birthday_dec_02',
    category: 'decor',
    vendor: 'Little Star Themes',
    packageName: 'Cartoon Theme Decor',
    base: 46000,
    area: AREA.janakpuri,
    includes: ['Theme backdrop', 'Cut-outs', 'Table props', 'Entry arch'],
    strengths: ['Great for kids themes', 'Custom color palette'],
    limitations: ['Licensed character props need confirmation'],
    negotiable: ['theme prop count', 'extra welcome standee'],
  }),
  listing({
    ref: 'birthday_dec_03',
    category: 'decor',
    vendor: 'Pastel Party Studio',
    packageName: 'Pastel Luxe Birthday Setup',
    base: 64000,
    area: AREA.rajouri,
    includes: ['Pastel backdrop', 'Premium cake table', 'Floral accents', 'Photo corner'],
    strengths: ['Premium photos', 'Elegant family event style'],
    limitations: ['More setup time required'],
    negotiable: ['flower mix', 'photo corner props'],
  }),
  listing({
    ref: 'birthday_dec_04',
    category: 'decor',
    vendor: 'Neon Bash Designers',
    packageName: 'Teen Neon Party Decor',
    base: 52000,
    area: AREA.dwarka,
    includes: ['Neon sign', 'LED strips', 'Dance corner props', 'Entry backdrop'],
    strengths: ['Strong teen party vibe', 'Works well with DJ setup'],
    limitations: ['Indoor power points needed'],
    negotiable: ['neon sign text', 'extra LED strip'],
  }),

  listing({
    ref: 'cake_01',
    category: 'cake',
    vendor: 'Sweet Layers Birthday Bakery',
    packageName: '2kg Designer Cake',
    base: 4500,
    area: AREA.hariNagar,
    includes: ['Custom cake design', 'Delivery', 'Candles', 'Knife set'],
    strengths: ['Budget-friendly', 'Quick design confirmation'],
    limitations: ['Fondant figures cost extra'],
    negotiable: ['free cupcake tasters', 'name topper'],
  }),
  listing({
    ref: 'birthday_cake_02',
    category: 'cake',
    vendor: 'Fondant Fairy Cakes',
    packageName: 'Theme Fondant Cake',
    base: 8500,
    area: AREA.rajouri,
    includes: ['Fondant theme cake', 'Edible prints', 'Cake topper', 'Delivery'],
    strengths: ['Detailed theme work', 'Good kids designs'],
    limitations: ['Needs final design one day earlier'],
    negotiable: ['topper style', 'cupcake bundle'],
  }),
  listing({
    ref: 'birthday_cake_03',
    category: 'cake',
    vendor: 'Cupcake Carnival',
    packageName: 'Cake + Cupcake Tower',
    base: 12000,
    area: AREA.janakpuri,
    includes: ['1.5kg cake', '36 cupcakes', 'Display stand', 'Delivery'],
    strengths: ['Great for school friends', 'Easy serving'],
    limitations: ['Stand return required'],
    negotiable: ['cupcake count', 'flavour mix'],
  }),
  listing({
    ref: 'birthday_cake_04',
    category: 'cake',
    vendor: 'Choco Wish Studio',
    packageName: 'Premium Chocolate Cake Table',
    base: 18000,
    area: AREA.motiNagar,
    includes: ['3kg cake', 'Brownie bites', 'Dessert jars', 'Cake table setup'],
    strengths: ['Premium dessert spread', 'Strong chocolate menu'],
    limitations: ['Requires chilled storage'],
    negotiable: ['dessert jar count', 'brownie flavour'],
  }),

  listing({
    ref: 'makeup_01',
    category: 'makeup',
    vendor: 'Glow Up Party Studio',
    packageName: 'Birthday Glam Makeup',
    base: 20000,
    area: AREA.rajouri,
    includes: ['Party makeup', 'Hair styling', 'Basic draping'],
    strengths: ['Good for milestone birthdays', 'Camera-friendly look'],
    limitations: ['Travel outside Delhi costs extra'],
    negotiable: ['hair accessory', 'family member add-on'],
  }),
  listing({
    ref: 'birthday_makeup_02',
    category: 'makeup',
    vendor: 'Soft Glam Artist Delhi',
    packageName: 'Soft Glam Look',
    base: 15000,
    area: AREA.hariNagar,
    includes: ['Soft glam makeup', 'Hair setting', 'Touch-up kit'],
    strengths: ['Natural finish', 'Quick setup'],
    limitations: ['No advanced hair accessories'],
    negotiable: ['touch-up extension', 'lash style'],
  }),
  listing({
    ref: 'birthday_makeup_03',
    category: 'makeup',
    vendor: 'Teen Sparkle Studio',
    packageName: 'Teen Birthday Styling',
    base: 12000,
    area: AREA.janakpuri,
    includes: ['Light makeup', 'Hair styling', 'Glitter-safe accents'],
    strengths: ['Age-appropriate styling', 'Fast service'],
    limitations: ['Parent approval needed for strong looks'],
    negotiable: ['hair clips', 'second look'],
  }),
  listing({
    ref: 'birthday_makeup_04',
    category: 'makeup',
    vendor: 'Family Glam Team',
    packageName: 'Host + Family Styling',
    base: 36000,
    area: AREA.dwarka,
    includes: ['Host makeup', '2 family touch-ups', 'Hair styling', 'Draping support'],
    strengths: ['Good for milestone family birthdays', 'Team arrives together'],
    limitations: ['Needs two dressing chairs'],
    negotiable: ['extra family member', 'early morning slot'],
  }),

  listing({
    ref: 'pho_01',
    category: 'photography',
    vendor: 'Birthday Frames Studio',
    packageName: 'Photo Coverage',
    base: 60000,
    area: AREA.motiNagar,
    includes: ['1 photographer', 'Cake-cutting coverage', '150 edited photos'],
    strengths: ['Close to West Delhi', 'Fast birthday delivery'],
    limitations: ['Video not included'],
    negotiable: ['same-day preview', 'extra edited photos'],
  }),
  listing({
    ref: 'pho_02',
    category: 'photography',
    vendor: 'Smiles & Stories Films',
    packageName: 'Photo + Reel Package',
    base: 56000,
    travel: 4000,
    additional: 4000,
    area: AREA.rajouri,
    includes: ['Photographer', 'Short reel', 'Family portraits', 'Online gallery'],
    strengths: ['Good social reels', 'Family portrait focus'],
    limitations: ['Single reel in base package'],
    negotiable: ['extra reel', 'printed album'],
  }),
  listing({
    ref: 'corp_photo_del_01',
    category: 'photography',
    vendor: 'Candid Cake Moments',
    packageName: 'Candid Birthday Coverage',
    base: 36000,
    area: AREA.subhash,
    includes: ['1 photographer', 'Candid coverage', '100 edited photos'],
    strengths: ['Best value photo option', 'Close to Hari Nagar'],
    limitations: ['No video'],
    negotiable: ['extra photo edits', 'basic reel add-on'],
  }),
  listing({
    ref: 'birthday_pho_04',
    category: 'photography',
    vendor: 'Flash Party Crew',
    packageName: 'Premium Photo + Highlight Film',
    base: 78000,
    area: AREA.dwarka,
    includes: ['2 photographers', 'Highlight film', 'Drone subject to permission', 'Album'],
    strengths: ['Premium memory package', 'Better for large parties'],
    limitations: ['Higher package total'],
    negotiable: ['album pages', 'second shooter timing'],
  }),

  listing({
    ref: 'ent_01',
    category: 'entertainment',
    vendor: 'Mini Magic Moments',
    packageName: 'Kids Magic Show',
    base: 16000,
    area: AREA.tilak,
    includes: ['45-minute magic show', 'Balloon art', 'Audience games'],
    strengths: ['Great for kids under 10', 'Interactive show'],
    limitations: ['Needs small stage area'],
    negotiable: ['extra game round', 'birthday child trick'],
  }),
  listing({
    ref: 'ent_02',
    category: 'entertainment',
    vendor: 'Groove Squad Juniors',
    packageName: 'DJ + Games Host',
    base: 24000,
    area: AREA.hariNagar,
    includes: ['DJ playlist', 'Party games', 'Dance games', 'Basic lights'],
    strengths: ['Strong all-age entertainment', 'Compact setup'],
    limitations: ['No large sound rig'],
    negotiable: ['extra game prizes', 'theme playlist'],
  }),
  listing({
    ref: 'birthday_ent_03',
    category: 'entertainment',
    vendor: 'Puppet Parade Delhi',
    packageName: 'Puppet Show + Story Time',
    base: 18000,
    area: AREA.pitampura,
    includes: ['Puppet show', 'Story narration', 'Photo session'],
    strengths: ['Good for younger kids', 'Low-volume entertainment'],
    limitations: ['Not ideal for teen birthdays'],
    negotiable: ['story theme', 'extra puppet character'],
  }),
  listing({
    ref: 'birthday_ent_04',
    category: 'entertainment',
    vendor: 'Teen Beat Party Co.',
    packageName: 'Teen Dance Party',
    base: 38000,
    area: AREA.dwarka,
    includes: ['DJ', 'Dance host', 'Party lights', 'Games'],
    strengths: ['Good for teen parties', 'High energy'],
    limitations: ['Venue noise rules must be checked'],
    negotiable: ['extra hour', 'custom playlist'],
  }),

  listing({
    ref: 'corp_anchor_del_01',
    category: 'anchor',
    vendor: 'Party Mic Host',
    packageName: 'Birthday Anchor',
    base: 18000,
    area: AREA.karolBagh,
    includes: ['Anchor', 'Game flow', 'Cake-cutting announcement', 'Prize coordination'],
    strengths: ['Keeps party flow simple', 'Bilingual hosting'],
    limitations: ['4 hours included'],
    negotiable: ['extra hour', 'custom game script'],
  }),
  listing({
    ref: 'birthday_anchor_02',
    category: 'anchor',
    vendor: 'Kids Carnival Host',
    packageName: 'Kids Games Anchor',
    base: 14000,
    area: AREA.janakpuri,
    includes: ['Kids anchor', 'Game props', 'Dance warmup'],
    strengths: ['Great for young kids', 'Props included'],
    limitations: ['No DJ console'],
    negotiable: ['extra game', 'return gift coordination'],
  }),
  listing({
    ref: 'birthday_anchor_03',
    category: 'anchor',
    vendor: 'Family Function Emcee',
    packageName: 'Family Birthday Emcee',
    base: 22000,
    area: AREA.rajouri,
    includes: ['Formal emcee', 'Family games', 'Announcements', 'Timeline coordination'],
    strengths: ['Good for milestone birthdays', 'Polished family style'],
    limitations: ['Sound system separate'],
    negotiable: ['script call', 'extra ceremony segment'],
  }),
  listing({
    ref: 'birthday_anchor_04',
    category: 'anchor',
    vendor: 'Hinglish Hype Host',
    packageName: 'Youth Party Host',
    base: 26000,
    area: AREA.rohini,
    includes: ['Hinglish host', 'Dance games', 'Audience engagement'],
    strengths: ['High energy', 'Teen and young adult friendly'],
    limitations: ['Travel timing from North Delhi'],
    negotiable: ['extra hour', 'custom roasts approval'],
  }),

  listing({
    ref: 'sound_01',
    category: 'sound',
    vendor: 'BassBox Birthday Audio',
    packageName: 'Small Party Sound',
    base: 18000,
    area: AREA.hariNagar,
    includes: ['PA speakers', '2 wireless mics', 'Mixer', 'Technician'],
    strengths: ['Close and affordable', 'Enough for hall parties'],
    limitations: ['No DJ lights'],
    negotiable: ['extra mic', 'sound check timing'],
  }),
  listing({
    ref: 'corp_sound_del_01',
    category: 'sound',
    vendor: 'Stage Spark AV',
    packageName: 'Sound + Party Lights',
    base: 32000,
    area: AREA.janakpuri,
    includes: ['PA system', 'Party lights', 'Wireless mics', 'Technician'],
    strengths: ['Good for DJ and games', 'Lighting included'],
    limitations: ['No projector in base'],
    negotiable: ['extra light pair', 'mic upgrade'],
  }),
  listing({
    ref: 'birthday_sound_03',
    category: 'sound',
    vendor: 'Clear Mic Events',
    packageName: 'Anchor Mic Kit',
    base: 12000,
    area: AREA.subhash,
    includes: ['Compact speakers', '2 mics', 'Operator'],
    strengths: ['Best for small family birthday', 'Very compact'],
    limitations: ['Not a dance-floor rig'],
    negotiable: ['extra mic', 'longer operator time'],
  }),
  listing({
    ref: 'birthday_sound_04',
    category: 'sound',
    vendor: 'Dance Floor Audio Delhi',
    packageName: 'Premium Dance Sound',
    base: 48000,
    area: AREA.dwarka,
    includes: ['High-power PA', 'Subwoofer', 'DJ console', 'Lighting truss'],
    strengths: ['Best for big dance party', 'Premium sound pressure'],
    limitations: ['Needs venue power clearance'],
    negotiable: ['extra playing hour', 'lighting scene package'],
  }),

  listing({
    ref: 'birthday_booth_01',
    category: 'photo_booth',
    vendor: 'Click Corner Booth',
    packageName: 'Instant Photo Booth',
    base: 22000,
    area: AREA.rajouri,
    includes: ['Photo booth', 'Props', 'Instant prints', 'Digital gallery'],
    strengths: ['Easy guest activity', 'Instant memories'],
    limitations: ['Print limit applies'],
    negotiable: ['extra prints', 'custom frame design'],
  }),
  listing({
    ref: 'birthday_booth_02',
    category: 'photo_booth',
    vendor: '360 Smile Booth',
    packageName: '360 Video Booth',
    base: 36000,
    area: AREA.motiNagar,
    includes: ['360 booth', 'Operator', 'Video sharing link', 'Props'],
    strengths: ['Social media friendly', 'Premium guest activity'],
    limitations: ['Needs open floor area'],
    negotiable: ['branding overlay', 'extra hour'],
  }),
  listing({
    ref: 'birthday_booth_03',
    category: 'photo_booth',
    vendor: 'Selfie Spot Studio',
    packageName: 'Selfie Wall + Props',
    base: 16000,
    area: AREA.hariNagar,
    includes: ['Selfie wall', 'Props basket', 'Ring light'],
    strengths: ['Budget booth alternative', 'Low space requirement'],
    limitations: ['No instant prints'],
    negotiable: ['custom hashtag board', 'extra props'],
  }),
  listing({
    ref: 'birthday_booth_04',
    category: 'photo_booth',
    vendor: 'Mirror Booth Magic',
    packageName: 'Magic Mirror Booth',
    base: 42000,
    area: AREA.dwarka,
    includes: ['Mirror booth', 'Touch screen', 'Instant prints', 'Attendant'],
    strengths: ['Premium interactive booth', 'Looks good in banquet halls'],
    limitations: ['Higher setup cost'],
    negotiable: ['print count', 'custom welcome screen'],
  }),

  listing({
    ref: 'birthday_fx_01',
    category: 'special_effects',
    vendor: 'Spark Safe FX',
    packageName: 'Cold Pyro Cake Entry',
    base: 18000,
    area: AREA.tilak,
    includes: ['Cold pyros', 'Operator', 'Safety setup'],
    strengths: ['Big cake entry moment', 'Compact setup'],
    limitations: ['Venue permission needed'],
    negotiable: ['pyro count', 'entry timing rehearsal'],
  }),
  listing({
    ref: 'birthday_fx_02',
    category: 'special_effects',
    vendor: 'Bubble Bash Effects',
    packageName: 'Bubble and Confetti Combo',
    base: 14000,
    area: AREA.hariNagar,
    includes: ['Bubble machine', 'Confetti poppers', 'Operator'],
    strengths: ['Kids-friendly effect', 'Good photos'],
    limitations: ['Cleanup support should be confirmed'],
    negotiable: ['extra confetti moment', 'bubble duration'],
  }),
  listing({
    ref: 'birthday_fx_03',
    category: 'special_effects',
    vendor: 'Foggy Frames FX',
    packageName: 'Low Fog Entry',
    base: 26000,
    area: AREA.rajouri,
    includes: ['Low fog machine', 'Operator', 'Entry coordination'],
    strengths: ['Premium entry visuals', 'Works with photo/video'],
    limitations: ['Indoor ventilation rules apply'],
    negotiable: ['fog duration', 'combined light cue'],
  }),
  listing({
    ref: 'birthday_fx_04',
    category: 'special_effects',
    vendor: 'Laser Lite Moments',
    packageName: 'Laser and Haze Party Look',
    base: 34000,
    area: AREA.rohini,
    includes: ['Mini laser setup', 'Haze machine', 'Operator'],
    strengths: ['Teen party mood', 'Pairs well with DJ'],
    limitations: ['Needs dark indoor setup'],
    negotiable: ['laser scenes', 'extra hour'],
  }),

  listing({
    ref: 'birthday_ceremony_01',
    category: 'ceremony',
    vendor: 'Blessing Moments Pandit',
    packageName: 'Birthday Puja Ritual',
    base: 9000,
    area: AREA.hariNagar,
    includes: ['Pandit ji', 'Basic puja samagri list', 'Blessing ritual', 'Muhurat guidance'],
    strengths: ['Simple family ritual', 'Good for first birthdays'],
    limitations: ['Samagri purchase billed separately'],
    negotiable: ['samagri kit', 'extra mantra duration'],
  }),
  listing({
    ref: 'birthday_ceremony_02',
    category: 'ceremony',
    vendor: 'Satvik Sankalp Services',
    packageName: 'Ayush Havan for Kids',
    base: 15000,
    area: AREA.janakpuri,
    includes: ['Pandit team', 'Havan setup', 'Samagri support', 'Family sankalp'],
    strengths: ['Good for family birthdays', 'Structured ritual flow'],
    limitations: ['Needs ventilation approval indoors'],
    negotiable: ['samagri inclusion', 'shorter ritual format'],
  }),
  listing({
    ref: 'birthday_ceremony_03',
    category: 'ceremony',
    vendor: 'Family Blessings Delhi',
    packageName: 'Naamkaran / Birthday Blessing',
    base: 12000,
    area: AREA.rajouri,
    includes: ['Pandit ji', 'Ritual checklist', 'Family guidance'],
    strengths: ['Good for naming and birthday events', 'Bilingual explanations'],
    limitations: ['Decor not included'],
    negotiable: ['extra family sankalp', 'samagri checklist call'],
  }),
  listing({
    ref: 'birthday_ceremony_04',
    category: 'ceremony',
    vendor: 'Shubh Day Rituals',
    packageName: 'Premium Family Puja',
    base: 22000,
    area: AREA.dwarka,
    includes: ['Two-pandit team', 'Samagri coordination', 'Havan kund setup', 'Ritual timeline'],
    strengths: ['Better for larger families', 'More complete ritual support'],
    limitations: ['Longer setup time'],
    negotiable: ['samagri bundle', 'short ritual version'],
  }),

  listing({
    ref: 'trans_01',
    category: 'transport',
    vendor: 'Party Shuttle Delhi',
    packageName: 'Guest Shuttle Vans',
    base: 15000,
    area: AREA.subhash,
    includes: ['2 shuttle vans', '8-hour city duty', 'Pickup coordination'],
    strengths: ['Close to West Delhi', 'Simple guest movement'],
    limitations: ['Only two vehicles in base'],
    negotiable: ['extra pickup point', 'extra hour'],
  }),
  listing({
    ref: 'corp_transport_del_01',
    category: 'transport',
    vendor: 'NCR Birthday Fleet',
    packageName: 'Tempo Traveller Package',
    base: 42000,
    area: AREA.hariNagar,
    includes: ['2 tempo travellers', 'Driver coordination', 'Route planning', '8-hour duty'],
    strengths: ['Good for group movement', 'Pickup coordination included'],
    limitations: ['Extra hours charged separately'],
    negotiable: ['vehicle branding', 'extra pickup point'],
  }),
  listing({
    ref: 'birthday_transport_03',
    category: 'transport',
    vendor: 'Family Ride Desk',
    packageName: 'Cab Coordination Desk',
    base: 26000,
    area: AREA.rajouri,
    includes: ['Cab coordinator', '6 cab slots', 'Guest call support'],
    strengths: ['Useful for elders', 'Flexible cab movement'],
    limitations: ['Actual cab count must be locked'],
    negotiable: ['extra cab slot', 'late-night drop'],
  }),
  listing({
    ref: 'birthday_transport_04',
    category: 'transport',
    vendor: 'Luxury Arrival Cars',
    packageName: 'Premium Arrival Car',
    base: 38000,
    area: AREA.dwarka,
    includes: ['Premium car', 'Decor ribbon', 'Driver', '4-hour duty'],
    strengths: ['Good for grand birthday entry', 'Photo-friendly arrival'],
    limitations: ['Limited duty hours'],
    negotiable: ['extra hour', 'car decor upgrade'],
  }),

  listing({
    ref: 'birthday_stay_01',
    category: 'accommodation',
    vendor: 'Comfort Rooms West Delhi',
    packageName: 'Family Room Block',
    base: 52000,
    area: AREA.janakpuri,
    includes: ['5 room-night block', 'Breakfast', 'Early check-in request'],
    strengths: ['Useful for outstation family', 'Near West Delhi venues'],
    limitations: ['Room availability must be reconfirmed'],
    negotiable: ['extra room night', 'late checkout'],
  }),
  listing({
    ref: 'birthday_stay_02',
    category: 'accommodation',
    vendor: 'Guest Nest Suites',
    packageName: 'Suite Stay Package',
    base: 78000,
    area: AREA.rajouri,
    includes: ['3 suites', 'Breakfast', 'Welcome snacks'],
    strengths: ['Premium family stay', 'Good for milestone birthdays'],
    limitations: ['Higher room tariff'],
    negotiable: ['welcome snack choice', 'extra bed'],
  }),
  listing({
    ref: 'birthday_stay_03',
    category: 'accommodation',
    vendor: 'Budget Family Stay Desk',
    packageName: 'Budget Hotel Rooms',
    base: 36000,
    area: AREA.karolBagh,
    includes: ['6 standard rooms', 'Basic breakfast', 'Check-in support'],
    strengths: ['Budget-friendly stay', 'Good room count'],
    limitations: ['Longer drive to West Delhi venues'],
    negotiable: ['room upgrade', 'extra breakfast'],
  }),
  listing({
    ref: 'birthday_stay_04',
    category: 'accommodation',
    vendor: 'Celebration Stay Concierge',
    packageName: 'Guest Stay Coordination',
    base: 64000,
    area: AREA.dwarka,
    includes: ['Hotel shortlisting', 'Room block coordination', 'Guest check-in desk'],
    strengths: ['Good for larger guest lists', 'Coordination included'],
    limitations: ['Final hotel rates can vary'],
    negotiable: ['check-in desk hours', 'welcome hamper'],
  }),

  listing({
    ref: 'birthday_hospitality_01',
    category: 'hospitality',
    vendor: 'Welcome Desk Crew',
    packageName: 'Guest Welcome Desk',
    base: 18000,
    area: AREA.hariNagar,
    includes: ['2 welcome staff', 'Guest list handling', 'Gift desk support'],
    strengths: ['Keeps arrival smooth', 'Good for family events'],
    limitations: ['Only 4 hours included'],
    negotiable: ['extra staff', 'longer desk hours'],
  }),
  listing({
    ref: 'birthday_hospitality_02',
    category: 'hospitality',
    vendor: 'Gift Desk Managers',
    packageName: 'Gift and Return Gift Desk',
    base: 14000,
    area: AREA.rajouri,
    includes: ['Gift tagging', 'Return gift handover', 'Desk staff'],
    strengths: ['Useful for kids parties', 'Simple tracking'],
    limitations: ['Inventory list must be provided'],
    negotiable: ['extra desk staff', 'gift label design'],
  }),
  listing({
    ref: 'birthday_hospitality_03',
    category: 'hospitality',
    vendor: 'Guest Care Delhi',
    packageName: 'Family Guest Coordination',
    base: 32000,
    area: AREA.janakpuri,
    includes: ['4 coordinators', 'Guest seating support', 'Elder assistance'],
    strengths: ['Good for larger gatherings', 'Elder-friendly support'],
    limitations: ['Transport coordination separate'],
    negotiable: ['extra coordinator', 'family protocol briefing'],
  }),
  listing({
    ref: 'birthday_hospitality_04',
    category: 'hospitality',
    vendor: 'Kids Party Care Team',
    packageName: 'Kids Activity Supervision',
    base: 28000,
    area: AREA.rohini,
    includes: ['Activity supervisors', 'Queue management', 'Parent support'],
    strengths: ['Useful with games and booths', 'Reduces parent load'],
    limitations: ['Not childcare replacement'],
    negotiable: ['extra supervisor', 'activity rotation plan'],
  }),

  listing({
    ref: 'birthday_invite_01',
    category: 'invitation',
    vendor: 'Digital Invite Lab',
    packageName: 'WhatsApp Video Invite',
    base: 7000,
    area: AREA.hariNagar,
    includes: ['Animated invite', '2 revisions', 'Share-ready video'],
    strengths: ['Fast and affordable', 'Easy WhatsApp sharing'],
    limitations: ['No print cards'],
    negotiable: ['extra revision', 'music change'],
  }),
  listing({
    ref: 'birthday_invite_02',
    category: 'invitation',
    vendor: 'Print Party Cards',
    packageName: 'Printed Birthday Invites',
    base: 12000,
    area: AREA.motiNagar,
    includes: ['100 printed cards', 'Envelope set', 'Basic design'],
    strengths: ['Traditional printed card option', 'Good for family invites'],
    limitations: ['Delivery timeline depends on approval'],
    negotiable: ['paper upgrade', 'extra 25 cards'],
  }),
  listing({
    ref: 'birthday_invite_03',
    category: 'invitation',
    vendor: 'Theme Invite Studio',
    packageName: 'Custom Theme Invite Kit',
    base: 18000,
    area: AREA.rajouri,
    includes: ['Video invite', 'Static invite', 'RSVP form', 'Theme graphics'],
    strengths: ['Matches decor theme', 'Useful RSVP link'],
    limitations: ['Needs theme locked early'],
    negotiable: ['extra language version', 'countdown story'],
  }),
  listing({
    ref: 'birthday_invite_04',
    category: 'invitation',
    vendor: 'Premium Invite Concierge',
    packageName: 'Digital + Print Invite Bundle',
    base: 32000,
    area: AREA.dwarka,
    includes: ['Video invite', '150 printed cards', 'RSVP tracker', 'Reminder creatives'],
    strengths: ['Complete invite workflow', 'Good for milestone events'],
    limitations: ['Higher design budget'],
    negotiable: ['print quantity', 'reminder creative count'],
  }),

  listing({
    ref: 'corp_stream_del_01',
    category: 'live_streaming',
    vendor: 'Live Memory Stream',
    packageName: 'Single Camera Birthday Stream',
    base: 45000,
    area: AREA.motiNagar,
    includes: ['1 camera setup', 'Streaming operator', 'Private YouTube link'],
    strengths: ['Good for remote relatives', 'Operator included'],
    limitations: ['Venue internet must be checked'],
    negotiable: ['recording copy', 'stream test'],
  }),
  listing({
    ref: 'birthday_stream_02',
    category: 'live_streaming',
    vendor: 'Family Stream Desk',
    packageName: 'Phone + Camera Hybrid Stream',
    base: 28000,
    area: AREA.hariNagar,
    includes: ['Camera operator', 'Mobile backup', 'Private link'],
    strengths: ['Budget stream option', 'Backup device included'],
    limitations: ['Basic production quality'],
    negotiable: ['extra recording copy', 'test call'],
  }),
  listing({
    ref: 'birthday_stream_03',
    category: 'live_streaming',
    vendor: 'Two Cam Celebration Live',
    packageName: 'Two-Camera Live Stream',
    base: 72000,
    area: AREA.dwarka,
    includes: ['2 cameras', 'Switcher', 'Streaming operator', 'Recording copy'],
    strengths: ['Better viewing experience', 'Good for stage moments'],
    limitations: ['Higher space and power needs'],
    negotiable: ['camera count', 'highlight clip'],
  }),
  listing({
    ref: 'birthday_stream_04',
    category: 'live_streaming',
    vendor: 'Remote Family Broadcast',
    packageName: 'Premium Private Broadcast',
    base: 96000,
    area: AREA.karolBagh,
    includes: ['2 cameras', 'Audio feed', 'Private page', 'Recording delivery'],
    strengths: ['Most polished stream', 'Good audio feed'],
    limitations: ['Internet and audio desk access required'],
    negotiable: ['private page branding', 'backup internet'],
  }),
].map((l) => {
  const cb = { base: 0, travel: 0, additional: 0, ...l.costBreakdown };
  return {
    ...l,
    costBreakdown: cb,
    price: cb.base + cb.travel + cb.additional,
    description: NOTE,
    isDemo: true,
    isActive: true,
  };
});

/** Reset and reseed demo listings only. Development/staging helper, never production. */
export async function seedDemoListings() {
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Refusing to seed demo listings when NODE_ENV=production');
  }
  const removed = await DemoListing.deleteMany({});
  const inserted = await DemoListing.insertMany(DEMO_LISTINGS, { ordered: true });
  return { inserted: inserted.length, removed: removed.deletedCount || 0, total: DEMO_LISTINGS.length };
}
